// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fradjgwtxymkmrpulbyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyYWRqZ3d0eHlta21ycHVsYnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzA4NDcsImV4cCI6MjA1OTcwNjg0N30.vY_5Y_2yTroyixAmQtl5tXZFDsS930nTcC_31uEUviQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);